// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiOYxn0WHPHAJVfPkvNPhqipDxCHvhzA',
    appId: '1:96089127226:web:701a46f0860bfd54fcb803',
    messagingSenderId: '96089127226',
    projectId: 'business-whatsapp-87b28',
    authDomain: 'business-whatsapp-87b28.firebaseapp.com',
    storageBucket: 'business-whatsapp-87b28.firebasestorage.app',
    measurementId: 'G-QTHHCN6Q77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvAUq5_uCoQ97JEZVx47MalIsoWApGxOk',
    appId: '1:96089127226:android:a9ed6194c04a8a1afcb803',
    messagingSenderId: '96089127226',
    projectId: 'business-whatsapp-87b28',
    storageBucket: 'business-whatsapp-87b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kIZbKW2MQ_-DSkftUfHlyAiCPrITqMI',
    appId: '1:96089127226:ios:744cf6b1ecdda7e8fcb803',
    messagingSenderId: '96089127226',
    projectId: 'business-whatsapp-87b28',
    storageBucket: 'business-whatsapp-87b28.firebasestorage.app',
    iosBundleId: 'com.example.businessWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kIZbKW2MQ_-DSkftUfHlyAiCPrITqMI',
    appId: '1:96089127226:ios:744cf6b1ecdda7e8fcb803',
    messagingSenderId: '96089127226',
    projectId: 'business-whatsapp-87b28',
    storageBucket: 'business-whatsapp-87b28.firebasestorage.app',
    iosBundleId: 'com.example.businessWhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQiOYxn0WHPHAJVfPkvNPhqipDxCHvhzA',
    appId: '1:96089127226:web:856d3be45eb7209efcb803',
    messagingSenderId: '96089127226',
    projectId: 'business-whatsapp-87b28',
    authDomain: 'business-whatsapp-87b28.firebaseapp.com',
    storageBucket: 'business-whatsapp-87b28.firebasestorage.app',
    measurementId: 'G-441C1DKZGP',
  );
}
