// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvnaIGM1n4RN3qLrIkVwH5-HONQqATAqc',
    appId: '1:42834520968:web:5bcc0e23c46d3a2bd7e83d',
    messagingSenderId: '42834520968',
    projectId: 'whatsapp-test-panel',
    authDomain: 'whatsapp-test-panel.firebaseapp.com',
    storageBucket: 'whatsapp-test-panel.firebasestorage.app',
    measurementId: 'G-5Q57N3J7W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzkA-vtCZOXoFGFmNfiEegDQssu7g-an0',
    appId: '1:42834520968:android:00a0979b3554c326d7e83d',
    messagingSenderId: '42834520968',
    projectId: 'whatsapp-test-panel',
    storageBucket: 'whatsapp-test-panel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_QSJYnOyl_w86fLOpu9Ekb89emfsj7Y',
    appId: '1:42834520968:ios:ebae56208b5314e4d7e83d',
    messagingSenderId: '42834520968',
    projectId: 'whatsapp-test-panel',
    storageBucket: 'whatsapp-test-panel.firebasestorage.app',
    iosBundleId: 'com.adminpanel.adminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_QSJYnOyl_w86fLOpu9Ekb89emfsj7Y',
    appId: '1:42834520968:ios:ebae56208b5314e4d7e83d',
    messagingSenderId: '42834520968',
    projectId: 'whatsapp-test-panel',
    storageBucket: 'whatsapp-test-panel.firebasestorage.app',
    iosBundleId: 'com.adminpanel.adminpanel',
  );
}
